name: Node.js CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      #- run: npm config set fetch-retry-mintimeout 20000
      #- run: npm config set fetch-retry-maxtimeout 120000
      #- run: npm config set fetch-timeout 300000
      - run: yarn install
      - run: yarn run build
      - run: yarn run eslint
      - run: yarn run test
        env:
          CI: true

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          push: false
